package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"example.com/tech-ip-sem2-graphql/graph/model"
	"example.com/tech-ip-sem2-graphql/internal/store"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	id := fmt.Sprintf("t_%03d", len(r.Store.List())+1)

	task := r.Store.CreateTask(id, input.Title, input.Description)
	return toGraphTask(task), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	task, ok := r.Store.UpdateTask(id, func(taskTitle *string, taskDescription **string, taskDone *bool) {
		if input.Title != nil {
			*taskTitle = *input.Title
		}
		if input.Description != nil {
			*taskDescription = input.Description
		}
		if input.Done != nil {
			*taskDone = *input.Done
		}
	})
	if !ok {
		return nil, fmt.Errorf("task not found")
	}

	return toGraphTask(task), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	return r.Store.DeleteTask(id), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	storedTasks := r.Store.List()
	result := make([]*model.Task, 0, len(storedTasks))
	for _, t := range storedTasks {
		result = append(result, toGraphTask(t))
	}

	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	task, ok := r.Store.GetByID(id)
	if !ok {
		return nil, nil
	}

	return toGraphTask(task), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func toGraphTask(t *store.Task) *model.Task {
	return &model.Task{
		ID:          t.ID,
		Title:       t.Title,
		Description: t.Description,
		Done:        t.Done,
	}
}
