package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"errors"
	"tech-ip-sem2-gql-vs-rest/graph/model"
	"tech-ip-sem2-gql-vs-rest/internal/task"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	item, err := r.Service.Create(task.CreateInput{
		Title:       input.Title,
		Description: input.Description,
	})
	if err != nil {
		return nil, err
	}

	return toGraphTask(item), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	item, err := r.Service.Update(id, task.UpdateInput{
		Title:       input.Title,
		Description: input.Description,
		Done:        input.Done,
	})
	if err != nil {
		return nil, err
	}

	return toGraphTask(item), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	items := r.Service.List()
	result := make([]*model.Task, 0, len(items))
	for _, item := range items {
		result = append(result, toGraphTask(item))
	}

	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	item, err := r.Service.Get(id)
	if err != nil {
		if errors.Is(err, task.ErrTaskNotFound) {
			return nil, err
		}
		return nil, err
	}

	return toGraphTask(item), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func toGraphTask(item task.Task) *model.Task {
	return &model.Task{
		ID:          item.ID,
		Title:       item.Title,
		Description: item.Description,
		Done:        item.Done,
	}
}
